"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function SettingsForm({ settings }) {
  const router = useRouter(); const [values, setValues] = useState({ businessHours: settings.business_hours || "", afterHoursNote: settings.after_hours_note || "", emergencyServiceAvailable: settings.emergency_service_available ?? true, announcement: settings.announcement || "", announcementEnabled: settings.announcement_enabled || false }); const [state, setState] = useState("idle"); const [message, setMessage] = useState("");
  const change = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setState("saving"); setMessage(""); try { const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setState("saved"); setMessage("Business settings saved."); router.refresh(); } catch (error) { setState("error"); setMessage(error.message); } };
  return <form className="admin-card admin-form settings-form" onSubmit={submit}><h2>Safe business controls</h2><p>These operational details can be changed without editing site code. Services, license claims, SEO, navigation, and integrations remain developer-maintained.</p><div className="field"><label htmlFor="businessHours">Business hours</label><textarea id="businessHours" rows="3" value={values.businessHours} onChange={(event) => change("businessHours", event.target.value)} placeholder="Example: Monday–Friday, 8 AM–5 PM" /></div><div className="field"><label htmlFor="afterHoursNote">After-hours note</label><textarea id="afterHoursNote" rows="3" value={values.afterHoursNote} onChange={(event) => change("afterHoursNote", event.target.value)} /></div><label className="switch-row"><span><strong>Emergency-service messaging</strong><small>Show the emergency call section on the homepage.</small></span><input type="checkbox" checked={values.emergencyServiceAvailable} onChange={(event) => change("emergencyServiceAvailable", event.target.checked)} /></label><hr /><div className="field"><label htmlFor="announcement">Temporary announcement</label><textarea id="announcement" rows="3" value={values.announcement} onChange={(event) => change("announcement", event.target.value)} placeholder="Example: Scheduling update or temporary service notice" /></div><label className="switch-row"><span><strong>Show announcement</strong><small>Display this message at the top of the public homepage.</small></span><input type="checkbox" checked={values.announcementEnabled} onChange={(event) => change("announcementEnabled", event.target.checked)} /></label>{message && <div className={`admin-feedback ${state}`}>{message}</div>}<button className="button button-dark" type="submit" disabled={state === "saving"}>{state === "saving" ? "Saving…" : "Save business settings"}</button></form>;
}

