import Link from "next/link";
import { notFound } from "next/navigation";
import { getAdminLead, LEAD_STATUSES } from "@/lib/data";
import { estimateServiceOptions } from "@/data/services";
import LeadEditor from "@/components/admin/LeadEditor";

function serviceName(value) { return estimateServiceOptions.find((item) => item.value === value)?.label || value; }
function Detail({ label, value }) { if (!value) return null; return <div><dt>{label}</dt><dd>{Array.isArray(value) ? value.join(", ") : value}</dd></div>; }

export default async function LeadDetailPage({ params }) {
  const { id } = await params; const lead = await getAdminLead(id); if (!lead) notFound(); const fullName = `${lead.first_name} ${lead.last_name}`.trim(); const address = [lead.property_address, lead.city, lead.zip].filter(Boolean).join(", ");
  return <><header className="admin-page-header"><div><Link href="/admin/leads" className="admin-back">← All leads</Link><h1>{fullName}</h1><span>{lead.reference} · Received {new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(lead.created_at))}</span></div><span className={`status-pill large status-${lead.status}`}>{LEAD_STATUSES.find((item) => item.value === lead.status)?.label}</span></header><div className="lead-detail-grid"><div className="admin-stack"><section className="admin-card lead-contact-card"><h2>Customer & property</h2><div className="quick-contact"><a className="button button-dark" href={`tel:${lead.phone}`}>Call {lead.phone}</a>{lead.email && <a className="button button-outline" href={`mailto:${lead.email}`}>Email {lead.email}</a>}</div><dl className="detail-list"><Detail label="Name" value={fullName} /><Detail label="Phone" value={lead.phone} /><Detail label="Email" value={lead.email} /><Detail label="Property" value={address} /><Detail label="Contact preference" value={[lead.preferred_contact_method, lead.best_contact_time].filter(Boolean).join(" · ")} /></dl></section><section className="admin-card"><h2>Original request</h2><dl className="detail-list"><Detail label="Service" value={lead.services.map(serviceName)} /><Detail label="Urgency" value={lead.urgency} /><Detail label="Job description" value={lead.job_description} /><Detail label="Approximate count" value={lead.approximate_count} /><Detail label="Preferred timeframe" value={lead.preferred_timeframe} /><Detail label="Customer notes" value={lead.customer_notes} /><Detail label="Source" value={lead.source === "contact" ? "Contact form" : "Estimate form"} /></dl></section><section className="admin-card"><h2>Submitted photos</h2>{lead.photo_references?.length ? <div className="lead-photo-grid">{lead.photo_references.map((photo) => photo.signedUrl ? <a href={photo.signedUrl} target="_blank" rel="noopener noreferrer" key={photo.path}>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={photo.signedUrl} alt={`Submitted by ${fullName}: ${photo.originalName}`} /><span>Open full photo</span></a> : null)}</div> : <div className="admin-empty compact">No photos were submitted.</div>}</section></div><LeadEditor lead={lead} /></div></>;
}

