import Link from "next/link";
import { getDashboardData, LEAD_STATUSES } from "@/lib/data";

function niceService(value) { return String(value || "").replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export default async function AdminDashboardPage() {
  const data = await getDashboardData();
  return <><header className="admin-page-header"><div><p>Owner portal</p><h1>Dashboard</h1><span>A quick view of requests and recently managed content.</span></div><Link href="/admin/leads" className="button button-dark">View all leads</Link></header><section className="admin-stat-grid">{LEAD_STATUSES.map((status) => <Link href={`/admin/leads?status=${status.value}`} key={status.value}><span>{status.label}</span><strong>{data?.counts?.[status.value] || 0}</strong></Link>)}</section><div className="admin-dashboard-grid"><section className="admin-card"><div className="admin-card-heading"><div><h2>Recent submissions</h2><p>Newest estimate and contact requests</p></div><Link href="/admin/leads">View all</Link></div>{data?.recentLeads?.length ? <div className="admin-list">{data.recentLeads.map((lead) => <Link href={`/admin/leads/${lead.id}`} key={lead.id}><div><strong>{lead.first_name} {lead.last_name}</strong><span>{lead.services.map(niceService).join(", ")}</span></div><div><span className={`status-pill status-${lead.status}`}>{LEAD_STATUSES.find((item) => item.value === lead.status)?.label}</span><small>{new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(lead.created_at))}</small></div></Link>)}</div> : <div className="admin-empty">New estimate requests will appear here.</div>}</section><div className="admin-stack"><section className="admin-card"><div className="admin-card-heading"><div><h2>Recent gallery uploads</h2><p>{data?.recentGallery?.length || 0} shown</p></div><Link href="/admin/gallery">Manage</Link></div>{data?.recentGallery?.length ? <ul className="simple-admin-list">{data.recentGallery.map((item) => <li key={item.id}><span>{item.caption || "Untitled project photo"}</span><small>{item.published ? "Published" : "Draft"}</small></li>)}</ul> : <div className="admin-empty compact">No uploads yet.</div>}</section><section className="admin-card"><div className="admin-card-heading"><div><h2>Recent testimonials</h2><p>{data?.recentTestimonials?.length || 0} shown</p></div><Link href="/admin/testimonials">Manage</Link></div>{data?.recentTestimonials?.length ? <ul className="simple-admin-list">{data.recentTestimonials.map((item) => <li key={item.id}><span>{item.customer_name}</span><small>{item.published ? "Published" : "Draft"}</small></li>)}</ul> : <div className="admin-empty compact">No testimonials yet.</div>}</section></div></div></>;
}

