import { business } from "@/data/business";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "Privacy Policy", description: `How ${business.name} handles information submitted through this website.`, path: "/privacy" });

export default function PrivacyPage() {
  return <><header className="page-hero legal-hero"><div className="shell"><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p>Last updated September 20, 2026</p></div></header><article className="shell legal-copy"><h2>Information we collect</h2><p>When you request an estimate or contact CutPro, we collect the information you choose to provide, such as your name, phone number, email, property address, job details, contact preferences, and photos.</p><h2>How we use it</h2><p>We use submitted information to review your request, contact you about the requested service, manage the potential job, maintain business records, prevent abuse, and operate this website.</p><h2>Photos and service providers</h2><p>Submitted estimate photos are stored privately with a managed storage provider. We also use service providers for website hosting, database operations, authentication, email delivery, analytics when configured, and spam prevention. They process information only as needed to provide those services.</p><h2>Retention and disclosure</h2><p>We retain request information for operational and recordkeeping needs, then remove it according to the business&apos;s retention practices. We do not sell customer personal information. We may disclose information when required by law or needed to protect people, property, or the service.</p><h2>Your choices</h2><p>You may choose not to upload photos or provide an email address. A phone number is required so CutPro can follow up. Browser settings and available consent tools can limit optional analytics.</p><h2>Security</h2><p>We use reasonable technical and organizational measures, including access controls and private storage for estimate photos. No internet system can guarantee absolute security.</p><h2>Contact</h2><p>For privacy questions or requests, call <a href={business.phoneHref}>{business.phoneDisplay}</a>. A dedicated privacy email or mailing address will be added when confirmed by CutPro.</p></article></>;
}

