import Link from "next/link";
import { getAdminLeads, LEAD_STATUSES } from "@/lib/data";
import { estimateServiceOptions } from "@/data/services";

function niceService(value) { return estimateServiceOptions.find((item) => item.value === value)?.label || value; }

export default async function LeadsPage({ searchParams }) {
  const query = await searchParams; const filters = { search: query.search || "", status: query.status || "", service: query.service || "" }; const leads = await getAdminLeads(filters);
  return <><header className="admin-page-header"><div><p>Estimate manager</p><h1>Leads</h1><span>Search customer facts, filter the queue, and open a record for follow-up.</span></div></header><form className="lead-filters" method="get"><div className="field"><label htmlFor="leadSearch">Search</label><input id="leadSearch" name="search" defaultValue={filters.search} placeholder="Name, phone, email, address, or reference" /></div><div className="field"><label htmlFor="statusFilter">Status</label><select id="statusFilter" name="status" defaultValue={filters.status}><option value="">All statuses</option>{LEAD_STATUSES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><div className="field"><label htmlFor="serviceFilter">Service</label><select id="serviceFilter" name="service" defaultValue={filters.service}><option value="">All services</option>{estimateServiceOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><button type="submit" className="button button-dark">Apply filters</button><Link href="/admin/leads" className="button button-outline">Clear</Link></form><section className="admin-card lead-table-card"><div className="admin-card-heading"><div><h2>{leads.length} lead{leads.length === 1 ? "" : "s"}</h2><p>Newest submissions appear first.</p></div></div>{leads.length ? <div className="lead-table"><div className="lead-table-head"><span>Customer</span><span>Request</span><span>Status</span><span>Received</span></div>{leads.map((lead) => <Link href={`/admin/leads/${lead.id}`} className="lead-table-row" key={lead.id}><div><strong>{lead.first_name} {lead.last_name}</strong><small>{lead.phone}{lead.email ? ` · ${lead.email}` : ""}</small></div><div><strong>{lead.services.map(niceService).join(", ")}</strong><small>{[lead.property_address, lead.city].filter(Boolean).join(", ") || "No address supplied"}</small></div><div><span className={`status-pill status-${lead.status}`}>{LEAD_STATUSES.find((item) => item.value === lead.status)?.label}</span></div><div><strong>{new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(lead.created_at))}</strong><small>{lead.reference}</small></div></Link>)}</div> : <div className="admin-empty">No leads match these filters.</div>}</section></>;
}

